### ISSUE TITLE
Build warning - dereferencing type-punned pointer will break strict-aliasing rules

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [json-parser/json-parser#134]
The warning is emitted by GCC with `-Wall` or `-Wstrict-aliasing`:
```
gcc -fPIC -g -O2 -Wstrict-aliasing -c json.c
json.c: In function ‘new_value’:
json.c:162:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             value->_reserved.object_mem = (*(char **) &value->u.object.values) + values_size;
             ^~~~~
json.c: In function ‘json_parse_ex’:
json.c:425:25: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
                         (*(json_char **) &top->u.object.values) += string_length + 1;
                         ^
```

**Comment by LB--** [comment]
Just to double check, there's currently no PR to address this yet, right? I got a bit confused when checking through things.

**Comment by DimitriPapadopoulos** [comment]
I'm afraid there is no PR indeed. I'm not certain yet how to handle this, actually I am not event certain what the warning means as my C is rusty. I am open to suggestions :-)

Just thought I'd open an issue not to forget about it.

**Comment by LB--** [comment]
Thanks for clarifying :)

Having seen these particular lines of code now, I guess the intent is to have perfect tight packing with no wasted bytes, which means having to cast pointers around in ways that break strict aliasing. I wonder if this could actually be a performance concern on RISC platforms like ARM where memory alignment is more important, either way I'll have to dig deeper to figure out if the current code actually poses a problem or not with compiler optimizations.
