### ISSUE TITLE
Use size_t for memory size

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [json-parser/json-parser#138]
The C standard library consistently uses `size_t` for variables related to memory size. See for example _malloc_(), _memset_(), _sizeof_().

The maximum value of an object of `size_t` type is:
* [`SIZE_MAX`, defined in `<limits.h>`](https://en.cppreference.com/w/c/types/limits) starting with C99,
* [`((size_t)(-1))`, if `SIZE_MAX` is not defined](https://stackoverflow.com/questions/44401965/how-to-get-size-max-in-c89).

Note that we cannot change `unsigned long`to `size_t` everywhere without modifying the API, so we will probably have to live with this exception:
```c
typedef struct
{
   unsigned long max_memory;
   [...]
} json_settings;
```

**Comment by DimitriPapadopoulos** [comment]
I am aware `size_t` is not perfect (see for example [On the use and abuse of size_t](https://www.duskborn.com/posts/on-the-use-and-abuse-of-size_t/)) but it looks like the best solution in this context, as it is available in C89 and fully consistent with the C standard library.

**Comment by LB--** [comment]
Thank you for that link, I forgot until now that `size_t` could be smaller than `uintptr_t`. This has me rethinking how to handle #139, perhaps we should use a progressive enhancement approach instead where we just merge #127 and then later add code to switch to `uintptr_t` when we have access to `UINTPTR_MAX` (since apparently `uintptr_t` is optional to implement - I assume presence of the macro implies presence and usability of the type).

**Comment by DimitriPapadopoulos** [comment]
I believe `size_t` is good enough for our needs and I would stick to it. Two reasons, by order of importance:
1. At least using ANSI C, we are unable to allocate or set memory chunks larger than `size_t` anyway: _malloc_(), _memset_() and the rest of the functions all expect a `size_t` type.
2. I don't see the need to address memory sizes larger than `size_t`.

I added the link for the sake of completeness. But I don't really agree with what's written in it.

**Comment by LB--** [comment]
> 1. At least using standard C, we are unable to allocate or set memory chunks larger than `size_t` anyway: _malloc_(), _memset_() and the rest of the functions all expect a `size_t` type.

This is a very good point... there may be potential for user-provided allocators to get around this limitation, but that does seem rather obscure. I suppose once you rebase your PR I'll take another look into this.
