### ISSUE TITLE
Documentation and `JSON_INT_T_OVERRIDDEN`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [json-parser/json-parser#148]
My intent was not that `JSON_INT_T_OVERRIDDEN` must be defined by end-users. Rather, if `json_int_t` is defined by end-users:

https://github.com/json-parser/json-parser/blob/3ec6608cee3619e4789488ef00503357c06093f0/json.h#L38

then `JSON_INT_T_OVERRIDDEN` is **automatically** defined:

https://github.com/json-parser/json-parser/blob/3ec6608cee3619e4789488ef00503357c06093f0/json.h#L50-L52

Therefore I would change:
> Example usage:
> * `-DJSON_INT_T_OVERRIDDEN -Djson_int_t=short`
> * `-DJSON_INT_T_OVERRIDDEN "-Djson_int_t=signed char" -DJSON_INT_MAX=127`
> * `-DJSON_INT_T_OVERRIDDEN "-Djson_int_t=long long"`
> * `-DJSON_INT_T_OVERRIDDEN -Djson_int_t=__int128`

to:
> Example usage:
> * `-Djson_int_t=short`
> * `"-D"son_int_t=signed char" -DJSON_INT_MAX=127`
> * `"-Djson_int_t=long long"`
> * `-Djson_int_t=__int128`

Is there a case where `JSON_INT_T_OVERRIDDEN` should be manually defined? I may have missed a use case.

**Comment by LB--** [comment]
Ah, I believe this was a misunderstanding on my part! My apologies.
