### ISSUE TITLE
Copy function

### ISSUE THREAD

**Issue by nattelog** [json-parser/json-parser#70]
Hi! 

It would be great to be able to copy one json_value to another. For instance: `json_value_copy(json_value* dest, json_value* src);`. So even after `json_value_free()` has been called on `src`, all values are still available in `dest`. Would it be of interest if I proposed a PR on this issue?

**Comment by harkue** [comment]
It seems like a ``deep-copy`` function.

**Comment by LB--** [comment]
Such a function might be better suited to going into json-builder instead. I can't really think of a scenario where you'd want to use json-parser exclusively and also copy the parsed data - without json-builder the parsed data is effectively immutable. If you have a counterexample though, I'd be curious to hear it!
