### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by LeeYoung624** [json-parser/json-parser#83]
Hey guys. The json-parser is a great lib, it's tiny enough and useful.
Have you ever considered to add `CMake` for json-parser? Therefore the json-parser can be compiled in different platforms.
Maybe I can make a PR for this if you like it.

**Comment by LB--** [comment]
There are a couple PRs now that try to add CMake support, though the value of it is questionable given how small the library is. In my experience it is easier (and safer) to just add the `json.c` source file to your main project's build system. Is there some issue in particular CMake would solve for you?

**Comment by LB--** [comment]
(Oops, clicked the wrong button)

**Comment by LB--** [comment]
Just noticed we have #59 already, let's move discussion to there.
