### ISSUE TITLE
Improve calculation of JSON_INT_MAX

### ISSUE THREAD

**Issue by trevnorris** [json-parser/json-parser#84]
From https://github.com/udp/json-parser/blob/e6426ae/json.c#L49-L55. That value can be calculated mathematically using `2**((n * 8) - 1) - 1`. Which can also be done using the following bit shift:
```c
static const json_int_t JSON_INT_MAX = (1L << ((8 * sizeof(json_int_t) - 1))) - 1
```

**Comment by harkue** [comment]
If Using
> ```c
> static const json_int_t JSON_INT_MAX = (1L << ((8 * sizeof(json_int_t) - 1))) - 1
> ```

It will trigger a warining such as:
```shell
json.c:48:1: warning: integer overflow in expression [-Woverflow]
 static const json_int_t JSON_INT_MAX = (1L << ((8 * sizeof(json_int_t) - 1))) - 1;
 ^~~~~~
```

**Comment by harkue** [comment]
Using this will be better:
```c
static const json_int_t JSON_INT_MAX = (json_int_t)((1UL<<((sizeof(json_int_t) * 8) - 1)) - 1);
```

**Comment by LB--** [comment]
Looks like this is being addressed in #102

**Comment by DimitriPapadopoulos** [comment]
Would that work on a platform where `long` (and hence `1UL`) is 32-bit, while `json_int_t` is defined (probably not in a portable way) to be 64-bit?

**Comment by DimitriPapadopoulos** [comment]
What was wrong with the previous definition of `JSON_INT_MAX` reverted by fcfa748? It's not clear to me.
```C
static const json_int_t JSON_INT_MAX = (((unsigned json_int_t)0 - (unsigned json_int_t)1) / (unsigned json_int_t)2);
```
