### ISSUE TITLE
License problems.

### ISSUE THREAD

**Issue by turbocat2001** [json-parser/json-parser#96]
I would like to use the library for a GPL 2 project. Is my project eligible for the GPL if it contains your code?

**Comment by DimitriPapadopoulos** [comment]
This looks like the [2-Clause BSD License](https://opensource.org/licenses/BSD-2-Clause).

See [Various Licenses and Comments about Them (FreeBSD license)](https://www.gnu.org/licenses/license-list.en.html#FreeBSD).

**Comment by udp** [comment]
As @DimitriPapadopoulos it is the FreeBSD/2-Clause BSD license, so it should be compatible with GPL.
